
/** 
 * This file is generated by the NotNot.AppSettings nuget package.
 * Do not edit this file directly, instead edit the appsettings.json files and rebuild the project.
 * `GenerateFilesWorker()` was called for Debug
**/
using System;
using System.Runtime.CompilerServices;
namespace AppSettingsGen._AppSettings._Logging;

[CompilerGenerated]
public partial class Debug {
   public AppSettingsGen._AppSettings._Logging._Debug.LogLevel? LogLevel{get; set;}

}
