
/** 
 * This file is generated by the NotNot.AppSettings nuget package  (v0.0.0.0).
 * Do not edit this file directly, instead edit the appsettings.json files and rebuild the project.
 * `GenerateFilesWorker()` was called for Logging
**/
using System;
using System.Runtime.CompilerServices;
namespace AppSettingsGen._AppSettings;

[CompilerGenerated]
internal partial class Logging {
   public AppSettingsGen._AppSettings._Logging.Debug? Debug{get; set;}
   public AppSettingsGen._AppSettings._Logging.Console? Console{get; set;}

}
