
/** 
 * This file is generated by the NotNot.AppSettings nuget package  (v0.0.0.0).
 * Do not edit this file directly, instead edit the appsettings.json files and rebuild the project.
 * `GenerateFilesWorker()` was called for Console
**/
using System;
using System.Runtime.CompilerServices;
namespace AppSettingsGen._AppSettings._Logging;

[CompilerGenerated]
internal partial class Console {
   public string? FormatterName{get; set;}
   public AppSettingsGen._AppSettings._Logging._Console.FormatterOptions? FormatterOptions{get; set;}

}
