
/** 
 * This file is generated by the NotNot.AppSettings nuget package  (v0.0.0-0.localDebug).
 * Do not edit this file directly, instead edit the appsettings.json files and rebuild the project.
 * `GenerateFilesWorker()` was called for SomeDevOption
**/
using System;
using System.Runtime.CompilerServices;
namespace AppSettingsGen._AppSettings;

[CompilerGenerated]
internal partial class SomeDevOption {
   public bool? Enabled{get; set;}
   public double? SomeValue{get; set;}

}
