
/** 
 * This file is generated by the NotNot.AppSettings nuget package  (v0.0.0.0).
 * Do not edit this file directly, instead edit the appsettings.json files and rebuild the project.
 * `GenerateFilesWorker()` was called for AppSettings
**/
using System;
using System.Runtime.CompilerServices;
namespace AppSettingsGen;

[CompilerGenerated]
internal partial class AppSettings {
   public string? AllowedHosts{get; set;}
   public AppSettingsGen._AppSettings.Logging? Logging{get; set;}
   public AppSettingsGen._AppSettings.Hello? Hello{get; set;}

}
