
/** 
 * This file is generated by the NotNot.AppSettings nuget package  (v0.0.0-0.localDebug).
 * Do not edit this file directly, instead edit the appsettings.json files and rebuild the project.
 * `GenerateFilesWorker()` was called for LogLevel
**/
using System;
using System.Runtime.CompilerServices;
namespace AppSettingsGen._AppSettings._Logging._Debug;

[CompilerGenerated]
internal partial class LogLevel {
   public string? Default{get; set;}
   public string? System{get; set;}
   public string? Microsoft{get; set;}

}
