
/** 
 * This file is generated by the NotNot.AppSettings nuget package  (v0.0.0.0).
 * Do not edit this file directly, instead edit the appsettings.json files and rebuild the project.
 * `GenerateFilesWorker()` was called for FormatterOptions
**/
using System;
using System.Runtime.CompilerServices;
namespace AppSettingsGen._AppSettings._Logging._Console;

[CompilerGenerated]
internal partial class FormatterOptions {
   public bool? IncludeScopes{get; set;}
   public string? TimestampFormat{get; set;}
   public bool? UseUtcTimestamp{get; set;}

}
