using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace NotNot.BlazorAnalyzers.XRay;

/// <summary>
/// Incremental source generator that parses .razor files and emits JSON metadata
/// for XRay debug overlay line number correlation.
/// </summary>
/// <remarks>
/// The generated XRayMetadata.g.cs contains:
/// - Static JSON string with element-to-line mappings
/// - Module Initializer that registers metadata with XRayRegistry on assembly load
/// </remarks>
[Generator(LanguageNames.CSharp)]
public class XRayMetadataGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Check for opt-out via AnalyzerConfig (set XRayGeneratorEnabled = false to disable)
        var optionsProvider = context.AnalyzerConfigOptionsProvider
            .Select((options, _) =>
            {
                options.GlobalOptions.TryGetValue("build_property.XRayGeneratorEnabled", out var enabled);
                return !string.Equals(enabled, "false", StringComparison.OrdinalIgnoreCase);
            });

        // Filter for .razor files from AdditionalTexts (registered via .props file)
        var razorFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase));

        // Transform each .razor file into parsed metadata
        var razorMetadata = razorFiles
            .Select(static (file, ct) =>
            {
                var content = file.GetText(ct)?.ToString() ?? "";
                var fileName = Path.GetFileName(file.Path);
                var elements = RazorElementParser.ParseElements(content);
                return (FileName: fileName, FilePath: file.Path, Elements: elements);
            });

        // Collect all metadata and combine with assembly name and enabled flag
        var collectedMetadata = razorMetadata.Collect();

        var assemblyAndMetadata = context.CompilationProvider
            .Combine(collectedMetadata)
            .Combine(optionsProvider);

        // Generate source
        context.RegisterSourceOutput(assemblyAndMetadata, static (spc, source) =>
        {
            var ((compilation, metadata), isEnabled) = source;

            // Skip generation if disabled via XRayGeneratorEnabled=false
            if (!isEnabled)
            {
                return;
            }

            var assemblyName = compilation.AssemblyName ?? "Unknown";

            var fileCount = metadata.Length;
            var filesWithElements = metadata.Where(m => m.Elements.Count > 0).ToArray();

            if (filesWithElements.Length == 0)
            {
                // Still generate a minimal file to confirm generator ran
                var minimalCode = $@"// <auto-generated/>
// XRay: No .razor files with elements found. Total AdditionalTexts: {fileCount}
// Files checked: {string.Join(", ", metadata.Take(5).Select(m => m.FileName))}
namespace {assemblyName};
internal static partial class XRayMetadata
{{
    internal static readonly string Json = ""{{}}"";
}}
";
                spc.AddSource("XRayMetadata.g.cs", SourceText.From(minimalCode, Encoding.UTF8));
                return;
            }

            // Sort files by name for deterministic output - prevents hot reload issues
            // caused by non-deterministic file enumeration order
            var code = GenerateSource(assemblyName,
                filesWithElements
                    .OrderBy(f => f.FileName, StringComparer.Ordinal)
                    .Select(f => (f.FileName, f.FilePath, f.Elements))
                    .ToImmutableArray());
            spc.AddSource("XRayMetadata.g.cs", SourceText.From(code, Encoding.UTF8));
        });
    }

    private static string GenerateSource(
        string assemblyName,
        ImmutableArray<(string FileName, string FilePath, IReadOnlyList<RazorElement> Elements)> metadata)
    {
        var sb = new StringBuilder();

        // Build JSON manually (no System.Text.Json in netstandard2.0 analyzers)
        var jsonBuilder = new StringBuilder();
        jsonBuilder.Append('{');

        bool firstFile = true;
        foreach (var (fileName, filePath, elements) in metadata)
        {
            if (!firstFile) jsonBuilder.Append(',');
            firstFile = false;

            // Compute relative path using assembly name as anchor (more reliable than pattern heuristics)
            var relativePath = ComputeRelativePath(filePath, fileName, assemblyName);

            // Use relativePath as the key to avoid filename collisions across directories
            // (e.g., Features/X/Components/ErrorDrawer.razor vs Components/ErrorDrawer.razor)
            jsonBuilder.Append('"');
            jsonBuilder.Append(EscapeJson(relativePath));
            jsonBuilder.Append("\":{\"relativePath\":\"");
            jsonBuilder.Append(EscapeJson(relativePath));
            jsonBuilder.Append("\",\"elements\":[");

            bool firstElement = true;
            foreach (var element in elements)
            {
                if (!firstElement) jsonBuilder.Append(',');
                firstElement = false;

                jsonBuilder.Append('{');
                jsonBuilder.Append("\"tag\":\"").Append(EscapeJson(element.Tag)).Append('"');
                jsonBuilder.Append(",\"line\":").Append(element.Line);

                // Attributes (sorted for deterministic output - Dictionary order is not guaranteed)
                if (element.Attributes.Count > 0)
                {
                    jsonBuilder.Append(",\"attrs\":{");
                    bool firstAttr = true;
                    foreach (var attr in element.Attributes.OrderBy(a => a.Key, StringComparer.Ordinal))
                    {
                        if (!firstAttr) jsonBuilder.Append(',');
                        firstAttr = false;
                        jsonBuilder.Append('"').Append(EscapeJson(attr.Key)).Append("\":\"");
                        jsonBuilder.Append(EscapeJson(attr.Value)).Append('"');
                    }
                    jsonBuilder.Append('}');
                }

                // Text content
                if (!string.IsNullOrEmpty(element.Text))
                {
                    jsonBuilder.Append(",\"text\":\"").Append(EscapeJson(element.Text)).Append('"');
                }

                // Conditional depth (used in scoring penalty: -3 per level)
                jsonBuilder.Append(",\"conditionalDepth\":").Append(element.ConditionalDepth);
                // NOTE: siblingIndex and domOrder removed (2026-01-01) - never consumed by JS matcher

                jsonBuilder.Append('}');
            }

            jsonBuilder.Append("]}");
        }

        jsonBuilder.Append('}');

        // Generate C# source
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {assemblyName};");
        sb.AppendLine();
        sb.AppendLine("internal static partial class XRayMetadata");
        sb.AppendLine("{");
        sb.AppendLine("    internal static readonly string Json = \"\"\"");
        sb.AppendLine($"    {jsonBuilder}");
        sb.AppendLine("    \"\"\";");
        sb.AppendLine();
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        sb.AppendLine($"        NotNot.BlazorComponents.XRay.XRayRegistry.Register(\"{EscapeJson(assemblyName)}\", Json);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Compute a relative path that uniquely identifies the file within the project.
    /// Uses assembly name as anchor to find project folder, more reliable than pattern heuristics.
    /// </summary>
    /// <remarks>
    /// Strategy:
    /// 1. PRIMARY: Find assembly name in path - everything after is relative to project
    /// 2. FALLBACK: Pattern-based heuristics for edge cases where assembly name doesn't match folder
    /// </remarks>
    private static string ComputeRelativePath(string fullPath, string fileName, string assemblyName)
    {
        if (string.IsNullOrEmpty(fullPath))
            return fileName;

        // Normalize path separators
        var normalized = fullPath.Replace('\\', '/');

        // PRIMARY: Find assembly name in path (most reliable)
        // e.g., ".../Novaleaf.VibeOverwatch.Server/Novaleaf/VibeOverwatch/..." → "Novaleaf/VibeOverwatch/..."
        // Handle both exact match and common naming patterns (with/without dots)
        var assemblyMarkers = new[]
        {
            $"/{assemblyName}/",           // Exact: Novaleaf.VibeOverwatch.Server
            $"/{assemblyName.Replace(".", "")}/",  // No dots: NovaleafVibeOverwatchServer
        };

        foreach (var marker in assemblyMarkers)
        {
            var idx = normalized.IndexOf(marker, StringComparison.OrdinalIgnoreCase);
            if (idx >= 0)
            {
                return normalized.Substring(idx + marker.Length);
            }
        }

        // FALLBACK: Pattern-based heuristics for edge cases
        // NOTE: This path should rarely be hit when assembly name matches folder
        var patterns = new[] { "/Features/", "/Pages/", "/Shared/", "/Layout/", "/Components/" };
        foreach (var pattern in patterns)
        {
            var idx = normalized.IndexOf(pattern, StringComparison.OrdinalIgnoreCase);
            if (idx >= 0)
            {
                return normalized.Substring(idx + 1);
            }
        }

        // Last resort: just use the filename
        return fileName;
    }

    /// <summary>
    /// Escape special characters for JSON string values.
    /// </summary>
    internal static string EscapeJson(string value)
    {
        if (string.IsNullOrEmpty(value)) return value;

        var sb = new StringBuilder(value.Length);
        foreach (var c in value)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < 32)
                        sb.Append($"\\u{(int)c:x4}");
                    else
                        sb.Append(c);
                    break;
            }
        }
        return sb.ToString();
    }
}
