using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace NotNot.BlazorAnalyzers.XRay;

/// <summary>
/// Incremental source generator that parses .razor files and emits JSON metadata
/// for XRay debug overlay line number correlation.
/// </summary>
/// <remarks>
/// The generated XRayMetadata.g.cs contains:
/// - Static JSON string with element-to-line mappings
/// - Module Initializer that registers metadata with XRayRegistry on assembly load
/// </remarks>
[Generator(LanguageNames.CSharp)]
public class XRayMetadataGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Filter for .razor files from AdditionalTexts (registered via .props file)
        var razorFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase));

        // Transform each .razor file into parsed metadata
        var razorMetadata = razorFiles
            .Select(static (file, ct) =>
            {
                var content = file.GetText(ct)?.ToString() ?? "";
                var fileName = Path.GetFileName(file.Path);
                var elements = RazorElementParser.ParseElements(content);
                return (FileName: fileName, FilePath: file.Path, Elements: elements);
            });

        // Collect all metadata and combine with assembly name
        var collectedMetadata = razorMetadata.Collect();

        var assemblyAndMetadata = context.CompilationProvider
            .Combine(collectedMetadata);

        // Generate source
        context.RegisterSourceOutput(assemblyAndMetadata, static (spc, source) =>
        {
            var (compilation, metadata) = source;
            var assemblyName = compilation.AssemblyName ?? "Unknown";

            var fileCount = metadata.Length;
            var filesWithElements = metadata.Where(m => m.Elements.Count > 0).ToArray();

            if (filesWithElements.Length == 0)
            {
                // Still generate a minimal file to confirm generator ran
                var minimalCode = $@"// <auto-generated/>
// XRay: No .razor files with elements found. Total AdditionalTexts: {fileCount}
// Files checked: {string.Join(", ", metadata.Take(5).Select(m => m.FileName))}
namespace {assemblyName};
internal static partial class XRayMetadata
{{
    internal static readonly string Json = ""{{}}"";
}}
";
                spc.AddSource("XRayMetadata.g.cs", SourceText.From(minimalCode, Encoding.UTF8));
                return;
            }

            var code = GenerateSource(assemblyName, filesWithElements.Select(f => (f.FileName, f.FilePath, f.Elements)).ToImmutableArray());
            spc.AddSource("XRayMetadata.g.cs", SourceText.From(code, Encoding.UTF8));
        });
    }

    private static string GenerateSource(
        string assemblyName,
        ImmutableArray<(string FileName, string FilePath, IReadOnlyList<RazorElement> Elements)> metadata)
    {
        var sb = new StringBuilder();

        // Build JSON manually (no System.Text.Json in netstandard2.0 analyzers)
        var jsonBuilder = new StringBuilder();
        jsonBuilder.Append('{');

        bool firstFile = true;
        foreach (var (fileName, filePath, elements) in metadata)
        {
            if (!firstFile) jsonBuilder.Append(',');
            firstFile = false;

            // Compute relative path (remove common prefixes, normalize separators)
            var relativePath = ComputeRelativePath(filePath, fileName);

            jsonBuilder.Append('"');
            jsonBuilder.Append(EscapeJson(fileName));
            jsonBuilder.Append("\":{\"relativePath\":\"");
            jsonBuilder.Append(EscapeJson(relativePath));
            jsonBuilder.Append("\",\"elements\":[");

            bool firstElement = true;
            foreach (var element in elements)
            {
                if (!firstElement) jsonBuilder.Append(',');
                firstElement = false;

                jsonBuilder.Append('{');
                jsonBuilder.Append("\"tag\":\"").Append(EscapeJson(element.Tag)).Append('"');
                jsonBuilder.Append(",\"line\":").Append(element.Line);

                // Attributes
                if (element.Attributes.Count > 0)
                {
                    jsonBuilder.Append(",\"attrs\":{");
                    bool firstAttr = true;
                    foreach (var attr in element.Attributes)
                    {
                        if (!firstAttr) jsonBuilder.Append(',');
                        firstAttr = false;
                        jsonBuilder.Append('"').Append(EscapeJson(attr.Key)).Append("\":\"");
                        jsonBuilder.Append(EscapeJson(attr.Value)).Append('"');
                    }
                    jsonBuilder.Append('}');
                }

                // Text content
                if (!string.IsNullOrEmpty(element.Text))
                {
                    jsonBuilder.Append(",\"text\":\"").Append(EscapeJson(element.Text)).Append('"');
                }

                // Conditional depth
                jsonBuilder.Append(",\"conditionalDepth\":").Append(element.ConditionalDepth);

                // Sibling index
                jsonBuilder.Append(",\"siblingIndex\":").Append(element.SiblingIndex);

                // DOM order (primary discriminator for matching)
                jsonBuilder.Append(",\"domOrder\":").Append(element.DomOrder);

                jsonBuilder.Append('}');
            }

            jsonBuilder.Append("]}");
        }

        jsonBuilder.Append('}');

        // Generate C# source
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {assemblyName};");
        sb.AppendLine();
        sb.AppendLine("internal static partial class XRayMetadata");
        sb.AppendLine("{");
        sb.AppendLine("    internal static readonly string Json = \"\"\"");
        sb.AppendLine($"    {jsonBuilder}");
        sb.AppendLine("    \"\"\";");
        sb.AppendLine();
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        sb.AppendLine($"        NotNot.BlazorComponents.XRay.XRayRegistry.Register(\"{EscapeJson(assemblyName)}\", Json);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Compute a relative path that uniquely identifies the file within the project.
    /// Extracts the path after common patterns like "Components/" or "Features/".
    /// </summary>
    private static string ComputeRelativePath(string fullPath, string fileName)
    {
        if (string.IsNullOrEmpty(fullPath))
            return fileName;

        // Normalize path separators
        var normalized = fullPath.Replace('\\', '/');

        // Try to find meaningful path segments
        var patterns = new[] { "/Components/", "/Features/", "/Pages/", "/Shared/", "/Layout/" };
        foreach (var pattern in patterns)
        {
            var idx = normalized.IndexOf(pattern, StringComparison.OrdinalIgnoreCase);
            if (idx >= 0)
            {
                return normalized.Substring(idx + 1);  // Include the folder name but not leading slash
            }
        }

        // Fallback: just use the filename
        return fileName;
    }

    /// <summary>
    /// Escape special characters for JSON string values.
    /// </summary>
    internal static string EscapeJson(string value)
    {
        if (string.IsNullOrEmpty(value)) return value;

        var sb = new StringBuilder(value.Length);
        foreach (var c in value)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < 32)
                        sb.Append($"\\u{(int)c:x4}");
                    else
                        sb.Append(c);
                    break;
            }
        }
        return sb.ToString();
    }
}
