// Ported from InlineComposition (https://github.com/BlackWhiteYoshi/InlineComposition)
// Original work Copyright (c) 2023 BlackWhiteYoshi, licensed under MIT License
// Modified work Copyright (c) 2025 NotNot Project and Contributors
// See LICENSE for full attribution



namespace NotNot.Mixins;

public static partial class Attributes {
    public const string InlineFinalizerAttribute = $$"""
        // <auto-generated/>
        #pragma warning disable
        #nullable enable annotations


        #if !INLINECOMPOSITION_EXCLUDE_ATTRIBUTES

        using System;

        namespace NotNot.MixinsAttributes;

        /// <summary>
        /// The Method under this attribute will be inlined in the finalizer.
        /// </summary>
        [AttributeUsage(AttributeTargets.Method)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("NotNot.Mixins", "1.0.0")]
        internal sealed class InlineFinalizerAttribute : Attribute {
            /// <summary>
            /// Indicates whether this method gets inlined before the other finalizers or after.
            /// </summary>
            public bool First { get; init; }
        }

        #endif

        """;
}
