// Ported from InlineComposition (https://github.com/BlackWhiteYoshi/InlineComposition)
// Original work Copyright (c) 2023 BlackWhiteYoshi, licensed under MIT License
// Modified work Copyright (c) 2025 NotNot Project and Contributors
// See LICENSE for full attribution



namespace NotNot.Mixins;

public static partial class Attributes {
    public const string NoInlineAttribute = $$"""
        // <auto-generated/>
        #pragma warning disable
        #nullable enable annotations


        #if !INLINECOMPOSITION_EXCLUDE_ATTRIBUTES

        using System;

        namespace NotNot.MixinsAttributes;

        /// <summary>
        /// <para>Only usefule in a class/struct with a <see cref="InlineBaseAttribute"/>.</para>
        /// <para>Skips/Ignores this member.</para>
        /// </summary>
        [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property | AttributeTargets.Event | AttributeTargets.Method)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("NotNot.Mixins", "1.0.0")]
        internal sealed class NoInlineAttribute : Attribute { }

        #endif

        """;
}
