<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ItemGroup>
		<!--make this a private asset-->
		<PackageReference Update="NotNot.AppSettings" PrivateAssets="All"/>
	</ItemGroup>

	<PropertyGroup>
		<_NotNotAppSettingsAutoGlobNormalized>$([System.String]::Copy('$(NotNot_AppSettings_AutoGlob)').ToLowerInvariant())</_NotNotAppSettingsAutoGlobNormalized>
	</PropertyGroup>

	<ItemGroup Condition="'$(_NotNotAppSettingsAutoGlobNormalized)' == 'true'">
		<!--required so target project appsettings.json files are included for sourcegen scanning-->
		<AdditionalFiles Include="appsettings*.json" />
	</ItemGroup>

	<ItemGroup>
		<!--allow reading these properties from the target project .csproj-->
		<CompilerVisibleProperty Include="NotNot_AppSettings_GenPublic" />
		<CompilerVisibleProperty Include="NotNot_AppSettings_AutoGlob" />
	</ItemGroup>

</Project>